
message("[INFO] PROJECT_NAME = ${package_name}")
message("[INFO] CMAKE_BUILD_TYPE = ${CMAKE_BUILD_TYPE}")

set(build_dir "${CMAKE_BINARY_DIR}/${CMAKE_BUILD_TYPE}")
message("[INFO] MAKE_DIRECTORY = ${build_dir}")
file(MAKE_DIRECTORY ${build_dir})

include(GNUInstallDirs)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${build_dir}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${build_dir}/${CMAKE_INSTALL_LIBDIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${build_dir}/${CMAKE_INSTALL_BINDIR})
message("[INFO] CMAKE_ARCHIVE_OUTPUT_DIRECTORY = ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message("[INFO] CMAKE_LIBRARY_OUTPUT_DIRECTORY = ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
message("[INFO] CMAKE_RUNTIME_OUTPUT_DIRECTORY = ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
message("[INFO] CMAKE_CACHEFILE_DIR = ${CMAKE_CACHEFILE_DIR}")
message("[INFO] CMAKE_MODULE_PATH = ${CMAKE_MODULE_PATH}")
message("[INFO] CMAKE_PREFIX_PATH = ${CMAKE_PREFIX_PATH}")

# Crucial for vscode cpp_tool to reference source code
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)